# Generated by Django 6.0.3 on 2026-04-29 02:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo do usuário')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E‑mail único por usuário')),
                ('regiao', models.CharField(choices=[('CO', 'Centro-Oeste'), ('N', 'Norte'), ('NE', 'Nordeste'), ('SE', 'Sudeste'), ('S', 'Sul')], db_column='regiao', default=None, max_length=255, verbose_name='Região')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amapá'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado de Residência')),
                ('cidade', models.CharField(default='São Paulo', max_length=50)),
                ('zona', models.CharField(choices=[('N', 'Zona Norte'), ('L', 'Zona Leste'), ('S', 'Zona Sul'), ('O', 'Zona Oeste'), ('C', 'Zona Central'), ('X', 'Outras Zonas')], db_column='zona', max_length=1, null=True, verbose_name='Zona na cidade de residência')),
                ('password', models.CharField(db_column='senha', max_length=128, verbose_name='Senha')),
                ('joined_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('confiability', models.FloatField(blank=True, help_text='Avaliação de confiabilidade 0 a 5 estrelas. Se nulo, significa não avaliado.', null=True, verbose_name='Confiabilidade')),
                ('moderador', models.BooleanField(db_column='moderador', default=False)),
                ('administrador', models.BooleanField(db_column='administrador', default=False)),
                ('ativo', models.BooleanField(db_column='ativo', default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_api', models.CharField(blank=True, max_length=50, null=True, verbose_name='OLID (OpenLibrary ID)')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('autor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Autor')),
                ('capa_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da capa')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
                ('estado', models.CharField(choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('NORMAL', 'Normal'), ('DANIFICADO', 'Danificado')], db_column='estado', max_length=10, null=True, verbose_name='Estado de conservação')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para troca')),
                ('em_doacao', models.BooleanField(default=False, verbose_name='Disponível para doação')),
                ('id_dono', models.ForeignKey(db_column='id_dono', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador único da troca')),
                ('data_troca', models.DateField(default=django.utils.timezone.now, verbose_name='Data da troca')),
                ('rating', models.FloatField(blank=True, help_text='Avaliação de 0 a 5 estrelas. Se nulo, significa não avaliado.', null=True, verbose_name='Avaliação')),
                ('id_dono', models.ForeignKey(db_column='id_dono', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_dono', to=settings.AUTH_USER_MODEL, verbose_name='Dono do livro')),
                ('id_interessado', models.ForeignKey(db_column='id_interessado', on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_interessado', to=settings.AUTH_USER_MODEL, verbose_name='Interessado no livro')),
                ('id_livro', models.ForeignKey(db_column='id_livro', on_delete=django.db.models.deletion.CASCADE, to='alexandria.livro', verbose_name='Livro em transação')),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
                'db_table': 'troca',
            },
        ),
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interesse', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Quando o Interesses foi registrado')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário interessado')),
                ('id_livro', models.ForeignKey(db_column='id_livro', on_delete=django.db.models.deletion.CASCADE, to='alexandria.livro', verbose_name='Livro de Interesses')),
            ],
            options={
                'verbose_name': 'Interesses',
                'verbose_name_plural': 'Interesses',
                'db_table': 'interesses',
                'constraints': [models.UniqueConstraint(fields=('id_usuario', 'id_livro'), name='unique_interesse')],
            },
        ),
    ]
