# Generated by Django 6.0.3 on 2026-04-29 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Interesses',
            options={},
        ),
        migrations.AddField(
            model_name='Interesses',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], default='P', max_length=1, verbose_name='Status da solicitação'),
        ),
        migrations.AlterField(
            model_name='Interesses',
            name='data_interesse',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='Interesses',
            name='id_livro',
            field=models.ForeignKey(db_column='id_livro', on_delete=django.db.models.deletion.CASCADE, to='alexandria.livro'),
        ),
        migrations.AlterField(
            model_name='Interesses',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
