# Generated by Django 6.0.3 on 2026-04-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria', '0002_alter_interesse_options_interesse_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interesses',
            name='unique_interesse',
        ),
        migrations.AddField(
            model_name='interesses',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='data_interesse',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='id_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexandria.livro'),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interesses',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='zona',
            field=models.CharField(choices=[('N', 'Norte'), ('L', 'Leste'), ('S', 'Sul'), ('O', 'Oeste'), ('C', 'Central'), ('X', 'Outras Zonas')], db_column='zona', max_length=1, null=True, verbose_name='Zona na cidade de residência'),
        ),
        migrations.AlterUniqueTogether(
            name='interesses',
            unique_together={('id_usuario', 'id_livro')},
        ),
        migrations.AlterModelTable(
            name='interesses',
            table=None,
        ),
    ]
