# Generated by Django 6.0.3 on 2026-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria', '0003_remove_interesses_unique_interesse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='zona',
            field=models.CharField(choices=[('N', 'Norte'), ('L', 'Leste'), ('S', 'Sul'), ('O', 'Oeste'), ('C', 'Central'), ('X', 'Outras')], db_column='zona', max_length=1, null=True, verbose_name='Zona na cidade de residência'),
        ),
    ]
