# Generated by Django 6.0.3 on 2026-05-12 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexandria', '0004_alter_usuario_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesses',
            options={'verbose_name': 'Interesse', 'verbose_name_plural': 'interesses'},
        ),
        migrations.RemoveField(
            model_name='troca',
            name='id_livro',
        ),
        migrations.RemoveField(
            model_name='troca',
            name='rating',
        ),
        migrations.AddField(
            model_name='troca',
            name='avaliacao_dono',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='troca',
            name='avaliacao_interessado',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='troca',
            name='comentario_dono',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='troca',
            name='comentario_interessado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='troca',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alexandria.livro'),
        ),
        migrations.AddField(
            model_name='troca',
            name='status',
            field=models.CharField(choices=[('E', 'Em andamento'), ('C', 'Concluída'), ('D', 'Desistida')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='troca',
            name='data_troca',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='troca',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='troca',
            name='id_dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_dono', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='troca',
            name='id_interessado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_interessado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='interesses',
            table='interesse',
        ),
    ]
